### ISSUE TITLE
Error in generated configure script

### ISSUE THREAD

**Issue by tleguern** [savonet/ocaml-lame#1]
Hello,

I am trying to get ocaml-lame working on OpenBSD and encountered a shell error in the configure script:

```
$ doas pkg_add automake-1.16.1 autoconf-2.69p2
$ export AUTOMAKE_VERSION=1.16
$ export AUTOCONF_VERSION=2.69
$ ./bootstrap CPPFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib"
...
checking for ocaml standard library path... ./configure[5579]: no: not found
...
```

In the file `m4/ocaml.m4` on line 231 there is a check for an utility named ocamlfind. If it is not present then the value of the variable `OCAMLFIND` becomes `no`.
In the very next block this variable is used without checking if it is a real executable:

```
OCAML_STDLIB=`$OCAMLFIND printconf stdlib`
```

I tried to patch the m4 code but, hum, failed.

**Comment by toots** [comment]
Thanks for reporting!
