### ISSUE TITLE
m4 files missing from 0.3.3 release

### ISSUE THREAD

**Issue by tleguern** [savonet/ocaml-lame#2]
On the release 0.3.3 [page](https://github.com/savonet/ocaml-lame/releases/tag/0.3.3) the link “Source code (tar.gz)” provides an archive with an empty m4 folder.

The link “ocaml-lame-0.3.3.tar.gz” is fine though.

**Comment by toots** [comment]
This is to be expected. The `m4/` directory is a git submodule and they are not exported via github's default setting. This has been improved in the current `master` branch.
